name: Docker Prod

on:
  workflow_dispatch:
  push:
    branches: [main]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} > .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env

          echo PK=${{ secrets.PK }} >> .env
          echo ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }} >> .env

          echo CLOB_API_KEY=${{ secrets.CLOB_API_KEY }} >> .env
          echo CLOB_SECRET=${{ secrets.CLOB_SECRET }} >> .env
          echo CLOB_PASS_PHRASE=${{ secrets.CLOB_PASS_PHRASE }} >> .env

          echo OPENVPN_USER=${{ secrets.OPENVPN_USER }} >> .env
          echo OPENVPN_PASSWORD=${{ secrets.OPENVPN_PASSWORD }} >> .env

      - name: Reset DB
        run: docker stop polybot-db || true && docker rm polybot-db || true

      - name: Docker run
        run: docker compose up -d --force-recreate --build

      - name: remove unused images, containers, volumes, and networks
        run: docker image prune -a -f --filter "until=24h" && docker container prune -f --filter "until=24h" && docker volume prune -f && docker network prune -f --filter "until=24h"
